#!/usr/bin/perl

use strict;
use warnings;
use JSON;

my $api = 'http://127.0.0.1:3000/lua/rest/v1/get/host/custom_data.lua?ifid=view:all&field_alias=ip,names,local_network_id,bytes.sent,bytes.rcvd';
my $limit = 10;
my $i = 0;
my @data;
my @rows;

my $content = decode_json(`/usr/bin/curl -H 'Content-Type: application/json' -s '$api'`);

if (!$content) {
    exit 1;
}

my @hosts;
foreach my $host (@{$content->{'rsp'}}) {
    next if not exists $host->{'local_network_id'};
    push(@hosts, {"host" => $host->{'ip'}, "sent" => int($host->{'bytes.sent'}), "rcvd" => int($host->{'bytes.rcvd'}), "tot" => int($host->{'bytes.sent'}) + int($host->{'bytes.rcvd'})});
}

@hosts = sort { $a->{"tot"} <=> $b->{"tot"}; } @hosts;

foreach (reverse @hosts) {
    last if ($i >= $limit);
    push(@rows, $_->{"host"});
    push(@data, [$_->{"sent"}, $_->{"rcvd"}]);
    $i++;
}

print encode_json({
        minerId => "hosttraffic-table",
        type => "table",
        unit => "bytes",
        aggregationType => "snapshot",
        columnHeader => ["sent", "received"],
        anonymizable => JSON::true,
        rowHeader => \@rows,
        rows => \@data
    });
