#!/usr/bin/perl
#
# Copyright (C) 2014  Nethesis srl

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# @author Giovanni Bezicheri <giovanni.bezicheri@nethesis.it>
# @author Edoardo Spadoni <edoardo.spadoni@nethesis.it>

#
# hosttraffic-table - a miner to collect data about host traffic
#
use strict;
use warnings;
use JSON;

my $api = 'http://127.0.0.1:3000/lua/hosts_traffic.lua';
my $limit = 10;
my $i = 0;
my @data;
my $content = {};
my @rows;
my $anonymize = shift || '';

system("/usr/bin/curl -s '$api' | grep '^{' > /tmp/result_ntopng");

my $json;
{
  open my $fh, "<", "/tmp/result_ntopng";
  $json = <$fh>;
  close $fh;
  system("/bin/rm -f /tmp/result_ntopng");
}

if ($json) {
   $content = decode_json($json);
} else {
    exit 1;
}

if (!$content) {
    exit 1;
}

foreach my $key (sort { int($a) <=> int($b) } keys %{$content->{'rank'}}) {
    my $ip = $content->{'rank'}{$key};
    last if ($i >= $limit);
    if ($anonymize eq 'true') {
        push(@rows, "host$i");
    } else {
        push(@rows, $ip);
    }
        push(@data, [ $content->{'hosts'}{$ip}{'total'}{'sent'}, $content->{'hosts'}{$ip}{'total'}{'received'} ]);
    $i++;
}

print encode_json({
        minerId => "hosttraffic-table",
        type => "table",
        unit => "bytes",
        aggregationType => "snapshot",
        columnHeader => ["sent", "received"],
        rowHeader => \@rows,
        rows => \@data
    });
