#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - info@nethesis.it
#
# This script is part of Dante.
#
# Dante is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# Dante is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dante.  If not, see COPYING.
#

use strict;
use warnings;
use JSON;
use File::Basename;

my $api = 'http://127.0.0.1:3000/lua/hosts_traffic.lua';
my $limit = 10;
my $content = {};
my @categories;
my @sent;
my @received;
my $i = 0;

system("/usr/bin/curl -s '$api' | grep '^{' > /tmp/result_ntopng_chart_bar");

my $json;
{
  open my $fh, "<", "/tmp/result_ntopng_chart_bar";
  $json = <$fh>;
  close $fh;
  system("/bin/rm -f /tmp/result_ntopng_chart_bar");
}

if ($json) {
   $content = decode_json($json);
} else {
    exit 1;
}

if (!$content) {
    exit 1;
}

foreach my $key (sort { int($a) <=> int($b) } keys %{$content->{'rank'}}) {
    my $ip = $content->{'rank'}{$key};
    last if ($i >= $limit);
    push(@categories, $ip);
    push(@sent,  $content->{'hosts'}{$ip}{'total'}{'sent'});
    push(@received,  $content->{'hosts'}{$ip}{'total'}{'received'});
    $i++;
}

print encode_json({
        minerId => basename($0),
        type => "chart",
        chartType => "bar",
        aggregationType => "snapshot",
        categories => \@categories,
        anonymizable => JSON::true,
	    unit => "bytes",
        series => [ { name => "sent", data => \@sent }, { name => "received", data => \@received }]
    });
