#!/usr/bin/perl

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - info@nethesis.it
#
# This script is part of Dante.
#
# Dante is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# Dante is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Dante.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use JSON;

my $value = 0;
my $cdb = esmith::ConfigDB->open_ro();
my $quota_status = $cdb->get_prop('dovecot', 'QuotaStatus') || 'disabled';
if ($quota_status eq 'enabled' && -f '/usr/libexec/nethserver/mail-quota') {
    my $quota = decode_json(`/usr/libexec/nethserver/mail-quota`);
    foreach (keys %$quota) {
        my $fields = $quota->{$_};
        $value += ($fields->{'size'} || 0);
    }
    $value = $value * 1024;
}

print encode_json({
        minerId => "mailsize-counter",
        type => "counter",
        trendType => "percentage",
        unit => "bytes",
        aggregationType => "snapshot",
        value => $value
    });

