#!/usr/bin/perl
#
# HostWebTraffic Miner
# Copyright (C) 2014  Nethesis srl

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# @author Giovanni Bezicheri <giovanni.bezicheri@nethesis.it>
# @author Edoardo Spadoni <edoardo.spadoni@nethesis.it>

#
# Total squid traffic
#
use strict;
use warnings;
use JSON;
use POSIX qw(strftime);

my $date = strftime "%Y%m%d", localtime;
my $total_file = "/var/lightsquid/$date/.total";
my $traffic = 0;

# run lightparser once
if (-f "/sbin/lightparser.pl" && ! -f $total_file) {
    system("/sbin/lightparser.pl -t /var/log/squid/access.log 2>/dev/null");
}

if (! -f $total_file) {
    exit 1;
}

if (-f $total_file) {
    open(my $fh, '<', $total_file);
    while (readline($fh)) {
        if ($_ =~ /size: (\d+)/) {
            $traffic = int($1);
            last;
        }
    }
    close($fh);
}

print encode_json({
        minerId => "squidtraffic-counter",
        type => "counter",
        title => "squidtraffic-counter",
        trendType => "percentage",
        unit => "bytes",
        aggregationType => "sum",
        value => $traffic,

    });
