---
sudo: required
language: go
git:
  depth: false

services:
    - docker
branches:
    only:
        - master
env:
   global:
    - DEST_ID=core
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e ENDPOINTS_PACK
        "
before_install:
    - sudo apt-get install curl python-software-properties npm python-setuptools -y
    - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - sudo apt-get install nodejs
    - sudo npm config set ca ""
    - sudo npm conf set strict-ssl false
    - sudo easy_install pip
    - sudo pip install transifex-client

install:
    - cd dist && ./prep-sources >/dev/null && cp -r ../.git .

script: >
    docker run -ti --name makerpms ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s *.spec
    && docker commit makerpms nethserver/build
    && docker run -ti ${EVARS}
    -e SECRET
    -e SECRET_URL
    -e AUTOBUILD_SECRET
    -e AUTOBUILD_SECRET_URL
    nethserver/build uploadrpms-travis

